# config.py
#
# Honest defaults reflecting what the thesis actually reports.
# (The previous file claimed a "SOTA-beating" configuration targeting 94.5%
# Dice on Kvasir-SEG; the thesis itself reports 0.896 Dice, 9.8 px HD95. Those
# inflated claims have been removed.)
#
# Ablation switches added (used by Models/hd_mixnet.py and Utils/losses.py):
#   BRANCH_MODE          : "both" | "cnn_only" | "swin_only"
#   USE_BAMF             : if False, fusion = concat + 1x1 conv
#   USE_EDGE_SUP         : if False, no ED/BE blocks and no edge loss
#   LAMBDA_HD            : set to 0.0 to disable the Hausdorff-DT term
#   THRESHOLD_SELECTION  : "dice" | "hd95" | "composite"
#                          controls how the best threshold is chosen on the
#                          validation set; "composite" uses
#                              score = dice - λ_thr * (hd95 / hd95_norm)
#                          with λ_thr = THRESHOLD_COMPOSITE_LAMBDA and
#                          hd95_norm = THRESHOLD_COMPOSITE_HD_NORM.
#
# Reproducibility:
#   SEED, VAL_SPLIT, IMG_SIZE, BATCH_SIZE, LEARNING_RATE, NUM_EPOCHS,
#   WEIGHT_DECAY, WARMUP_EPOCHS, GRAD_CLIP_NORM, all LAMBDA_* values, and the
#   train/val sample IDs are written to checkpoints/run_metadata.json at the
#   start of every training run (see train.py).

import os
import torch


class Config:
    # ------------------------------------------------------------------ env
    CPU_COUNT = os.cpu_count() or 4
    DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    SEED = 42
    NUM_WORKERS = min(4, CPU_COUNT)
    PIN_MEMORY = DEVICE.type == 'cuda'
    NON_BLOCKING = DEVICE.type == 'cuda'
    USE_AMP = DEVICE.type == 'cuda'
    USE_TF32 = DEVICE.type == 'cuda'
    USE_CHANNELS_LAST = DEVICE.type == 'cuda'
    USE_GRAD_CHECKPOINTING = DEVICE.type == 'cuda'
    PREFETCH_FACTOR = 2

    # ----------------------------------------------------------------- data
    DATA_ROOT = os.environ.get('KVASIR_DATA_ROOT', './Data/Kvasir')
    TRAIN_IMG_DIR = os.path.join(DATA_ROOT, 'images')
    TRAIN_MASK_DIR = os.path.join(DATA_ROOT, 'masks')

    # Cross-dataset roots (used by cross_dataset_eval.py). Optional - leave
    # the paths blank if the dataset is not on disk; the evaluator will skip
    # any missing dataset and report this in the output.
    CROSS_DATASETS = {
        'Kvasir-SEG':   os.environ.get('KVASIR_DATA_ROOT',  './Data/Kvasir'),
        'CVC-ClinicDB': os.environ.get('CVC_CLINIC_ROOT',   './Data/CVC-ClinicDB'),
        'CVC-ColonDB':  os.environ.get('CVC_COLON_ROOT',    './Data/CVC-ColonDB'),
        'ETIS-Larib':   os.environ.get('ETIS_ROOT',         './Data/ETIS-Larib'),
    }

    # ----------------------------------------------------------------- split
    # 80/10/10 train/val/test on Kvasir-SEG, generated by fixed seed.
    # train.py writes the actual sample IDs to run_metadata.json.
    VAL_SPLIT = 0.10
    TEST_SPLIT = 0.10

    # ---------------------------------------------------------------- model
    NUM_CLASSES = 1
    IMG_SIZE = 384
    RES2NET_SCALE = 4
    SWIN_WINDOW_SIZE = 7
    CNN_BASE_CHANNELS = 48
    SWIN_EMBED_DIM = 96
    SWIN_HEADS_STAGE1 = 3
    SWIN_HEADS_STAGE2 = 6
    SWIN_STAGE_DEPTHS = (2, 2)
    SWIN_MLP_RATIO = 4.0
    SWIN_DROP_PATH = 0.1

    # ----------------------------------------------------------- ablations
    # Defaults reproduce the full HD-MixNet of the thesis.
    BRANCH_MODE = 'both'       # 'both' | 'cnn_only' | 'swin_only'
    USE_BAMF = True            # if False, fusion is naive concat
    USE_EDGE_SUP = True        # if False, no ED/BE blocks and no edge loss

    # ------------------------------------------------------ training
    BATCH_SIZE = 16 if DEVICE.type == 'cuda' else 2
    ACCUMULATION_STEPS = 1
    LEARNING_RATE = 1e-4
    MIN_LEARNING_RATE = 1e-6
    NUM_EPOCHS = 100
    WARMUP_EPOCHS = 5
    WEIGHT_DECAY = 1e-4
    GRAD_CLIP_NORM = 1.0

    # -------------------------------------------------------- losses
    # Concrete lambda values (the thesis was missing these numerical values
    # in the prose - the reviewer flagged this).
    LAMBDA_STRUCT = 1.0
    LAMBDA_DICE = 0.5
    LAMBDA_BCE = 0.3
    LAMBDA_BOUNDARY = 0.30
    LAMBDA_HD = 0.10
    LAMBDA_EDGE = 0.20        # weight on the edge-head BCE auxiliary loss
    LAMBDA_AUX = 0.40         # weight on the auxiliary segmentation head

    STRUCTURE_POOL_KERNEL = 31
    BOUNDARY_LOSS_KERNEL = 5
    HD_ALPHA = 2.0
    HD_BINARIZE_THRESHOLD = 0.5
    HD_NORMALIZE = True

    MIN_BCE_POS_WEIGHT = 1.0
    MAX_BCE_POS_WEIGHT = 10.0

    # ---------------------------------------------------- validation
    DEFAULT_THRESHOLD = 0.5
    THRESHOLD_CANDIDATES = tuple(round(x * 0.01, 2) for x in range(20, 81, 5))

    # New: choose how the best threshold per epoch is picked.
    # The thesis text emphasises boundary quality but the implementation
    # selected the threshold that maximised Dice. The reviewer flagged this
    # as inconsistent. Set to "hd95" or "composite" to align with the
    # boundary claim.
    THRESHOLD_SELECTION = 'dice'    # 'dice' | 'hd95' | 'composite'
    THRESHOLD_COMPOSITE_LAMBDA = 0.05
    THRESHOLD_COMPOSITE_HD_NORM = 50.0   # pixels; used to scale HD95 into ~unit range

    USE_TTA = False
    VAL_USE_TTA = False
    USE_POST_PROCESSING = True
    POST_PROCESS_KERNEL = 5
    KEEP_LARGEST_COMPONENT = True
    MIN_COMPONENT_AREA_RATIO = 0.001
    VALIDATE_EVERY = 1
    HD95_EVERY = 1

    # ----------------------------------------------------- inference
    INFERENCE_IMG_SIZE = 384
    INFERENCE_BATCH_SIZE = 1
    USE_INFERENCE_TTA = False

    # ----------------------------------------------------- debugging
    STORE_LAYER_OUTPUTS = False

    # -------------------------------------------------- multi-seed eval
    # Used by run_ablations.py and the reproducibility scripts.
    EVAL_SEEDS = (42, 1337, 2024)
